//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAndClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string ID { get; set; }
        public string TaskName { get; set; }
        public string TaskContent { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Type { get; set; }
        public string AccountName { get; set; }
        public string Place { get; set; }
    }
}
